name: Deploy to Production

on:
  workflow_run:
    workflows:
      - "Run E2E test"
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          curl ${{ secrets.RENDER_PRODUCTION_DEPLOY_HOOK_URL }}