name: Deploy to Production

on:
  workflows:
    - "Run E2E test"
  types:
    - completed
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          curl ${{ secrets.RENDER_PRODUCTION_DEPLOY_HOOK_URL }}